services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - source: ..
        target: /app-name
        type: bind
    environment:
      PLACEHOLDER: value
    networks:
      - app-name

  mongo:
    image: mongo:latest
    networks:
      - app-name

networks:
  app-name:
    driver: bridge
    name: app-name-network
