services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - source: ..
        target: /app-name
        type: bind
    environment:
      PLACEHOLDER: value
    networks:
      - app-name

  mongo:
    image: mongo:latest
    networks:
      - app-name

  kafka:
    image: bitnami/kafka:3.9.0
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - app-name

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    volumes:
      - ${PWD}/ch_data:/var/lib/clickhouse
      - ${PWD}/ch_logs:/var/log/clickhouse-server
    networks:
      - app-name

networks:
  app-name:
    driver: bridge
    name: app-name-network
